purpose: clean_architecture_generator
version: "1.0.0"
role: distributed_systems_architect

description: |
  Generate production-ready Go projects with Clean Architecture, Domain-Driven Design (DDD),
  Event-Driven patterns, and Outbox Pattern. Optimized for distributed systems requiring
  high throughput, guaranteed event delivery, and 4-20x performance improvements.

instructions: |
  This template creates a complete Go project structure following:
  
  **Architecture Patterns (Non-Negotiable):**
  - Clean Architecture (4 layers: Domain, Application, Infrastructure, Interface)
  - Domain-Driven Design (Aggregates, Entities, Value Objects, Domain Services)
  - Event-Driven Architecture (Domain Events + Integration Events)
  - Outbox Pattern (Guaranteed event delivery with transactional consistency)
  - CQRS Lite (Command/Query separation)
  - Hybrid Repository Pattern (GORM for writes, pgxpool for reads)
  
  **Workflow:**
  1. Ask user 6 technical questions (database, cache, event broker, outbox notifier, API protocol, observability)
  2. Validate compatibility between answers (e.g., Postgres LISTEN/NOTIFY requires PostgreSQL)
  3. Generate project structure based on configuration
  4. Apply conditional templates based on user choices
  5. Create aggregates specific to user's domain
  6. Setup infrastructure clients (DB, cache, event broker)
  7. Implement Outbox Pattern with chosen notifier strategy
  8. Generate observability setup (metrics, health checks, logging)
  9. Create Docker Compose for local development
  10. Generate comprehensive documentation
  
  **Key Guidelines:**
  - ALWAYS start with task: "ask_technical_questions.md"
  - VALIDATE cross-dependencies before generating code
  - NEVER violate Clean Architecture layer dependencies
  - ENSURE all integration events use Outbox Pattern
  - PROVIDE performance benchmarks for critical operations
  - INCLUDE comprehensive testing structure (unit + integration)

metadata:
  category: distributed_systems
  difficulty: advanced
  estimated_time: 2-4 hours
  go_version: "1.24+"
  target_users:
    - Backend engineers building microservices
    - Teams requiring high-performance distributed systems
    - Projects needing guaranteed event delivery
    - Applications with complex business logic (DDD)
