instructions:
  - Before copying or replicating, the agent must present the `.ai-context` folder structure to the client for review and approval.
  - When using this context, the agent must carefully copy or replicate the entire `.ai-context` folder into the client's project, ensuring that no files or subfolders are missed.
  - All files, including dotfiles and documentation, are important for full functionality and should be preserved.
tasks:
  path: ./tasks/
  description: Agent-executable tasks. Each file is a task. To execute, use 'run task:<number>'.
  list:
    - README.md: Instructions and usage for adding and running tasks.
version: 1.0

rules:
  path: ./rules.md
  description: Project-wide coding conventions and error handling

knowledge:
  path: ./knowledge/
  description: Technical notes and ADRs with a README.md for guidance

apis:
  path: ./apis/
  description: OpenAPI/Swagger contracts with a README.md explaining usage

templates:
  path: ./templates/
  description: Code and test scaffolding templates, documented in README.md

goals:
  path: ./goals/
  description: Step-by-step executable tasks, each explained in README.md
