purpose: |
  This repository serves as a TEMPLATE HUB for .ai-context structures.
  The .ai-context folder in the root is FOR AGENTS maintaining this repository.
  The README.md serves as an index for external agents to find and use templates.

repository_role: template_hub_maintainer

instructions:
  - This .ai-context helps agents understand how to maintain and add new templates to this repository
  - Each template folder contains a complete .ai-context structure ready to be copied to client projects
  - Before adding any new template, follow the rules defined in ./rules.md
  - Always update the root README.md index when adding new templates
tasks:
  path: ./tasks/
  description: Agent-executable tasks. Each file is a task. To execute, use 'run task:<number>'.
  list:
    - README.md: Instructions and usage for adding and running tasks.
version: 1.0

rules:
  path: ./rules.md
  description: Project-wide coding conventions and error handling

knowledge:
  path: ./knowledge/
  description: Technical notes and ADRs with a README.md for guidance

apis:
  path: ./apis/
  description: OpenAPI/Swagger contracts with a README.md explaining usage

templates:
  path: ./templates/
  description: Templates for creating new .ai-context templates and documentation
  includes:
    - template-readme.md: README structure for new templates
    - template-aicontext-yaml.md: .aicontext.yaml configuration template
    - readme-index-structure.md: Root README.md index formatting guide

goals:
  path: ./goals/
  description: Step-by-step executable tasks, each explained in README.md
  
